# -*- coding: utf-8 -*-
"""berryBox_train_YOLOv8_det_small_2400_SCINet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Aum2tWIBwih7RGCTOmtTMpSw4BcvDZ1

# BerryBox Fruit Rot Object Detection

## Train YOLO V8 Object Detection Model

"""

## Step 0. Setup

### Load dependencies 

# Load YOLO
import ultralytics
ultralytics.checks()

from ultralytics import YOLO

# Load other libraries
import os
import torch
import time
import subprocess
import gc
import random
import shutil
import pandas as pd

proj_dir = os.getcwd()

# clear gpu cache if gpu is available
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    device = "0" # '0' or "0,1,2,3" depending on the number of GPUs available
    device = ",".join([str(x) for x in range(torch.cuda.device_count())])
    print("\nRunning on device: " + str(device))

# clear garbage
gc.collect()

# Define custom function
def run_shuffle_script(data_folder, ds_name):
    # shuffle the data, split into train, val, and test [70, 20, 10]
    # NOTE, the dataset must not be already split into train, val, and test in the data folder
    script_path = os.path.join("utils", "do_shuffle.py")
    process = subprocess.Popen(["python", script_path, data_folder, ds_name], stdout=subprocess.PIPE)
    time.sleep(10)
    process.terminate()
    print("Shuffling has been completed.")

# Flag - should the roboflow dataset be downloaded?
download_data = False
# Flag - should data be shuffled into train, val, and test?
shuffle_data = True
# Flag - should training be resumed?
resume_training = False

# Proportion of images to use for train/test/validation
p_val = 0.10
p_test = 0.10
p_train = 1 - (p_val + p_test)
p_total_use = 0.29

"""3. Download the Roboflow dataset if needed"""

# Download the dataset if requested
# nversion = 8
# nversion = 14
nversion = 17 # Latest working version
nversion = 20 # Test version using tablet 
workspace_name = "usdacranberrybreeding"
project_name = "berrybox_fruitrot_objdet"
from roboflow import Roboflow
rf = Roboflow(api_key="Q8hkEElVPqqFXfy81G46")
rf_project = rf.workspace(workspace_name).project(project_name)
version = rf_project.version(nversion)
if download_data:
    dataset = version.download("yolov8")
    dirname = project_name + "-" + str(nversion)
    os.rename(dirname, "BerryBox_ObjDet_Datasets/" + dirname)

"""4. Shuffle the dataset"""

# Shuffle the dataset using homemade code
data_folder = "BerryBox_ObjDet_Datasets"
# ds_name = "berrybox_berry_instanceseg-1"
ds_name = "berrybox_fruitrot_objdet-" + str(nversion)

data_path = data_folder + "/" + ds_name
data_path_shuf = data_path + "_shuffled"

if shuffle_data:
    # Delete the older shuffled dataset if present
    if os.path.exists(data_path_shuf):
        shutil.rmtree(data_path_shuf)

    # Copy the entire folder
    # !cp -r {data_path} {data_path_shuf}
    subprocess.run(["cp", "-r", data_path, data_path_shuf], check=True)

    # Edit the yaml file
    with open(os.path.join(data_path_shuf, "data.yaml"), "r") as f:
        lines = f.readlines()
    newlines = []
    line0 = lines[0]
    lines[0] = "path: " + proj_dir + "/" + data_path_shuf + "\n" + line0
    lines[1:4] = [line.replace("../", "") for line in lines[1:4]]
    # Edit the path to train, valid, and test
    for line in lines:
        if line.startswith("test:") or line.startswith("train:") or line.startswith("val:"):
            continue
        else:
            newlines.append(line)
    test_train_val = ['test: ../test/images\n', 'train: train/images\n', 'val: valid/images\n']
    newlines.extend(test_train_val)

    with open(os.path.join(data_path_shuf, "data.yaml"), "w") as f:
        f.writelines(newlines)

    # Rename the "train" folder "all"
    # !mv {data_path_shuf}/train {data_path_shuf}/all
    subprocess.run(["mv", data_path_shuf + "/train", data_path_shuf + "/all"], check=True)

    # List the basename of the images in the "all" folder
    all_image_path = data_path_shuf + "/all/images/"
    all_labels_path = data_path_shuf + "/all/labels/"
    # List basenames (i.e. sans extension)
    all_basenames = [".".join(x.split(".")[:-1]) for x in os.listdir(all_image_path)]

    # Determine the number of train/test/val images
    n_images = int(len(all_basenames) * p_total_use)
    n_val = int(p_val * n_images)
    n_test = int(p_test * n_images)
    n_train = n_images - (n_val + n_test)


    # Randomly sample basename for training/test/val
    train_basenames = random.sample(all_basenames, n_train)
    val_basenames = random.sample([x for x in all_basenames if x not in train_basenames], n_val)
    test_basenames = random.sample([x for x in all_basenames if x not in train_basenames + val_basenames], n_test)

    # Print the results
    print("Number of training images: " + str(len(train_basenames)))
    print("Number of validation images: " + str(len(val_basenames)))
    print("Number of testing images: " + str(len(test_basenames)))
    print("\n\n")

    # Create train/val/test folders (and delete them if they already exist)
    split_dirnames = ["train", "valid", "test"]
    # Iterate
    for dirname in split_dirnames:
        # splitdir = dataset.location + "/" + dirname
        splitdir = data_path_shuf + "/" + dirname
        if os.path.exists(splitdir):
            shutil.rmtree(splitdir)

        if dirname == "train":
            images = [x for x in os.listdir(all_image_path) if any([y in x for y in train_basenames])]
            labels = [x for x in os.listdir(all_labels_path) if any([y in x for y in train_basenames])]
        elif dirname == "val":
            images = [x for x in os.listdir(all_image_path) if any([y in x for y in val_basenames])]
            labels = [x for x in os.listdir(all_labels_path) if any([y in x for y in val_basenames])]
        else:
            images = [x for x in os.listdir(all_image_path) if any([y in x for y in test_basenames])]
            labels = [x for x in os.listdir(all_labels_path) if any([y in x for y in test_basenames])]

        os.mkdir(splitdir)
        subdirs = [splitdir + "/" + x for x in ["images", "labels"]]
        for subdir in subdirs:
            os.mkdir(subdir)

        # Copy images
        for image in images:
            shutil.copy(all_image_path + "/" + image, splitdir + "/images/" + image)

        # Copy labels
        for label in labels:
            shutil.copy(all_labels_path + "/" + label, splitdir + "/labels/" + label)

save_folder = data_path_shuf if shuffle_data else data_path
yaml_dir = os.path.join(save_folder, "data.yaml")

data_path_shuf

"""4. Set parameters"""

# specify training parameters
data = yaml_dir # path to yaml file
epochs = 600 # number of epochs to train
patience = 100 # early stopping patience
batch_size = 4 # -1 for auto else specify 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024 etc
img_size = 2400
cache = True # cache images for faster training
device = device # specify the device to use for training, options are "cpu", "0", "0,1,2,3", "auto"
workers = 1
model_size = "s" # ["n", "s", "m", "l"]
project = "BerryBox_Fruit_Rot_ObjDet" # project name
name = os.path.basename(save_folder) + "_" + model_size.title() + "_" + str(img_size) + "_v" + str(nversion)  # name of the model
exist_ok = True # existing project name, new name, or 'resume'
optimizer = "auto" # optimizer to use for training, options are "SGD", "Adam", "AdamW", "Adamax", "RMSprop", "RAdam", "auto"
verbose = True # print verbose output

# Augmentation hyperparameters
hsv_h = 0.2
hsv_s = 0.2
hsv_v = 0.2
degrees = 15
# degrees = 0
translate = 0.1
# translate = 0
scale = 0.5
shear = 0
perspective = 0
flipud = 0.3
fliplr = 0.3
mosaic = 0
mixup = 0
copy_paste = 0
crop_fraction = 0

name_val = name + "_val" # validation name
name_pred = name + "_pred" # Prediction output name

# # Weights to use for pre-training
# This one below resulted in mediocre accuracy when trained on Nano mode
# weights = proj_dir + "/../YOLOv8_SEG_code/BerryBox_Inst_Seg_Nano_2784/BerryBox_FruitRot_InstanceSeg-10_shuffled/weights/best.pt"

# This one also resulted in mediocre accuracy, but higher than the one above
# weights = proj_dir + "/../YOLOv8_SEG_code/BerryBox_Inst_Seg_Medium/BerryBox_FruitRot_InstanceSeg-10_shuffled/weights/best.pt"

"""## Step 1. Run model training"""

# clear garbage
gc.collect()

# Set model parameters
model_param = {
    "project": project,
    "name": name,
    "data": data,
    "epochs": epochs,
    "batch": batch_size,
    "imgsz": img_size,
    "optimizer": optimizer,
    "device": device,
    "verbose": verbose,
    "exist_ok": exist_ok,
    "patience": patience,
    "cache": cache,
    "workers":  workers,
    "hsv_h":  hsv_h,
    "hsv_s":  hsv_s,
    "hsv_v":  hsv_v,
    "degrees": degrees,
    "translate":  translate,
    "scale": scale,
    "shear": shear,
    "perspective":  perspective,
    "flipud":  flipud,
    "fliplr": fliplr,
    "mosaic": mosaic,
    "mixup": mixup,
    "copy_paste": copy_paste,
    "augment": True
}

# model training
# If resume training is false, train a new model
if not resume_training:
    model = YOLO('yolov8' + model_size + '.pt')  # load a pretrained model (recommended for training)
    # model = YOLO('yolov8' + model_size + '.pt').load(weights)

    # train the model
    results = model.train(**model_param)

else:
    path_last = os.path.join(project, name.replace("_shuffled", "") + "_shuffled", "weights", "last.pt")
    model = YOLO(path_last)
    results = model.train(resume = True, **model_param)

"""## Step 2. Run model validation"""

# Load the last model
model_path = proj_dir + "/" + project + "/" + name + "/weights/best.pt"
print(model_path)
model = YOLO(model_path)

# validate the model
val_results = model.val(
    data = data,
    project = project,
    name = name_val,
    batch = batch_size,
    imgsz = img_size,
    verbose = verbose,
    exist_ok = exist_ok,
    workers = workers
)


# Save the results of model validation to a CSV
precision = val_results.box.p
recall = val_results.box.r
f1 = val_results.box.f1
map50 = val_results.box.ap50
map5090 = val_results.box.ap

keys = [key for key in val_results.names if val_results.names[key] == "sound" or val_results.names[key] == "rotten"]

# Create a dictionary with the metrics
metrics_dict = {
    'Class_index': keys,
    'Class': [val_results.names[key] for key in keys],
    'Precision': precision,
    'Recall': recall,
    'F1': f1,
    'mAP50': map50,
    'mAP50-90': map5090
}

# Convert to a pandas DataFrame
df = pd.DataFrame(metrics_dict)
# Save the DataFrame to a CSV file
df_filename = os.path.join(str(val_results.save_dir), "validation_results.csv")
df.to_csv(df_filename, index=False)

print("Validation results saved to " + df_filename)

